### ISSUE TITLE
Nothing is rendered in production build

### ISSUE THREAD

**Issue by panstromek** [kaorun343/vue-youtube-embed#63]
Player works normally in development build (Webpack dev server, Quasar framework), but when I build the app and visit the page, nothing gets rendered. There is just empty div woth no iframe inside. Even if I prerender the app, it will prerender the iframe correctly but once I visit the page, video just blicks and disappears once Vue hydrates.

I don't know what info to include, I have a hard time tracking this down. There is no error, no warning, just nothing happens. I will try to downgrade and see what happens, because I already used this plugin many times and never had a problem.

**Comment by panstromek** [comment]
update - same problem for all versions since 1.0.0 - even versions that I previously used in the same project. No I am pretty confused..

**Comment by mortensassi** [comment]
same problem here

**Comment by riux** [comment]
the same problem, using nuxt and firebase hosting

**Comment by mortensassi** [comment]
@riux i fixed it by [using the other youtube-plugin](https://github.com/anteriovieira/vue-youtube)

**Comment by riux** [comment]
well try the other plugin but I still have the problem

**Comment by riux** [comment]
@mortensassi test with your recommendation but I still have the problem, remember that this happens when deploying in Firebase hosting, I am using nuxt, firebase functions and firebase hosting
